name: love_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  loading_animation_widget: ^1.3.0
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  # Social Sign In
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  
  # Utilities
  crypto: ^3.0.7
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  uuid: ^4.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_icon: true
  image_path: 'assets/app_icon/app_icon.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/
    - assets/svg/
    - assets/images/app_logo.png